import React from "react";
import Head from "next/head";
import Container from "@/components/common/container/container";
import Layout from "@/components/common/layout/layout";
import { ProductListItem } from "../../../lib/types/api";
import ImagesSlider from "@/components/common/images-slider/images-slider";

export type ProductPageProps = {
  product: ProductListItem;
};
const ProductPage = (props: ProductPageProps) => {
  return (
    <Layout>
      <Head>
        <title>{props.product.name} - WooNext</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <Container className="py-6 grid sm:grid-cols-12 gap-6">
          <div className="col-span-6">
            <ImagesSlider images={props.product.images} />
          </div>
          <div className="col-span-6">
            <h2 className="font-light text-4xl">{props.product.name}</h2>
            <p
              className="text-2xl my-4 text-gray-700"
              dangerouslySetInnerHTML={{ __html: props.product.price_html }}
            ></p>
            <div
              className="text-gray-600 tracking-wide"
              dangerouslySetInnerHTML={{ __html: props.product.description }}
            ></div>
          </div>
        </Container>
      </main>
    </Layout>
  );
};

export default ProductPage;
