import Head from "next/head";
import Container from "@/components/common/container/container";
import ProductsList from "@/components/common/products-list/products-list";
import CategoriesList from "@/components/common/categories-list/categories-list";

import type { ProductListItem, ProductCategoryItem } from "@/lib/types/api";
import Header from "@/components/common/header/header";

type CategoryPageProps = {
  products: ProductListItem[];
  categories: ProductCategoryItem[];
};

const CategoryPage = (props: CategoryPageProps) => {
  return (
    <>
      <Head>
        <title>WooNext</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <Header />
        {props.categories.length > 0 ? (
          <Container className="py-6">
            <h2 className="text-center font-medium text-3xl mb-6">Categories</h2>
            <CategoriesList
              categories={props.categories
                .filter((c) => c.slug !== "uncategorized")
                .sort((a, b) => a.menu_order - b.menu_order)}
            />
          </Container>
        ) : null}
        <Container className="py-6">
          <h2 className="text-center font-medium text-3xl mb-6">Products</h2>
          <ProductsList products={props.products} />
        </Container>
      </main>
    </>
  );
};

export default CategoryPage;
