import Link from "next/link";
import Head from "next/head";
import Layout from "@/components/common/layout/layout";
import Container from "@/components/common/container/container";
import ProductsList from "@/components/common/products-list/products-list";
import CategoriesList from "@/components/common/categories-list/categories-list";

import type {
  ProductListItem,
  ProductCategoryItem,
  BlogPostListItem,
  SlideshowItem,
} from "@/lib/types/api";
import BlogPostsList from "@/components/common/blog-posts-list/blog-posts-list";
import HeroSlider from "@/components/common/hero-slider/hero-slider";

type StorefrontProps = {
  featuredProducts: ProductListItem[];
  mainCategories: ProductCategoryItem[];
  blogPosts: BlogPostListItem[];
  slideshow: SlideshowItem;
};

const slides = [
  {
    title: "title",
    description: "description",
    image: {
      id: 4,
      src: "http://woocommercenextjsrestapi.local/wp-content/uploads/2023/03/pexels-pixabay-147411.jpg",
      alt: "",
      name: "large",
    },
  },
  {
    title: "title",
    description: "description",
    image: {
      id: 4,
      src: "http://woocommercenextjsrestapi.local/wp-content/uploads/2023/03/pexels-pixabay-147411.jpg",
      alt: "",
      name: "large",
    },
  },
];
export default function Storefront(props: StorefrontProps) {
  return (
    <Layout isHomepage={true} categories={props.mainCategories}>
      <Head>
        <title>WooNext</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <HeroSlider slideshow={props.slideshow} slides={slides} />
        <Container className="py-10">
          <h2 className="mb-6 text-3xl font-medium text-center">Categories</h2>
          <CategoriesList categories={props.mainCategories} />
        </Container>
        <Container className="py-10">
          <h2 className="mb-6 text-3xl font-medium text-center">Featured Products</h2>
          <ProductsList products={props.featuredProducts} />
        </Container>
        <div className="bg-black ">
          <Container className="py-10 flex flex-col items-center">
            <h2 className="mb-6 text-3xl font-medium text-center text-white">Blog</h2>
            <BlogPostsList blogPosts={props.blogPosts || []} darkMode={false} />
            <Link href="/blog">
              <button className="px-6 mt-6 py-1 text-lg font-light text-white transition-colors duration-200 border border-white border-solid rounded-full hover:bg-white hover:text-black">
                Show More
              </button>
            </Link>
          </Container>
        </div>
      </main>
    </Layout>
  );
}
