import ProductsList from "@/components/common/product-list/product-list";
import { ProductListItem } from "@/lib/types/api";
import Head from "next/head";

type StorefrontProps = {
  featuredProducts: ProductListItem[]
}

export default function Storefront(props: StorefrontProps) {
  return (
    <>
      <Head>
        <title>WooNext</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <ProductsList products={props.featuredProducts} />
      </main>
    </>
  );
}
