import Head from "next/head";
import Layout from "@/components/common/layout/layout";
import Container from "@/components/common/container/container";
import ProductsList from "@/components/common/products-list/products-list";
import CategoriesList from "@/components/common/categories-list/categories-list";

import type { ProductListItem, ProductCategoryItem } from "@/lib/types/api";

type StorefrontProps = {
  featuredProducts: ProductListItem[];
  mainCategories: ProductCategoryItem[];
};

export default function Storefront(props: StorefrontProps) {
  return (
    <Layout categories={props.mainCategories}>
      <Head>
        <title>WooNext</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <Container className="py-6">
          <h2 className="text-center font-medium text-3xl mb-6">Categories</h2>
          <CategoriesList categories={props.mainCategories} />
        </Container>
        <Container className="py-6">
          <h2 className="text-center font-medium text-3xl mb-6">Featured Products</h2>
          <ProductsList products={props.featuredProducts} />
        </Container>
      </main>
    </Layout>
  );
}
