import Head from "next/head";
import { useCart } from "@/lib/context/cartContext";
import Container from "@/components/common/container/container";
import Layout from "@/components/common/layout/layout";
import CartItemsList from "@/components/common/cart-items-list/cart-items-list";

import type { ProductCategoryItem } from "@/lib/types/api";

type CartPageProps = {
  mainCategories: ProductCategoryItem[];
};

const CartPage = (props: CartPageProps) => {
  const { cartItems } = useCart();
  return (
    <Layout categories={props.mainCategories}>
      <Head>
        <title>WooNext</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <Container className="py-10">
          <h2 className="mb-6 text-3xl font-medium text-left">Cart</h2>
          <CartItemsList cartItems={cartItems} />
        </Container>
      </main>
    </Layout>
  );
};

export default CartPage;
